// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1576928683);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1576928323);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1576928563);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1576928443);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1597990422);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1597990452);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 342);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.ctrlTab.migrated", true);
user_pref("browser.ctrlTab.recentlyUsedOrder", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1576928293);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.migration.version", 91);
user_pref("browser.newtabpage.activity-stream.impressionId", "{1c50e484-aa1d-4699-9775-0462929616bd}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1576857600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"pinTab\",\"addSearchEngine\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.sessionstore.resume_session_once", true);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20200217142647");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1597990393");
user_pref("browser.slowStartup.averageTime", 2374);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20200217142647");
user_pref("browser.startup.homepage_override.mstone", "73.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1597990393);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 2);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1576928294360");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.performance.recording.interval", 1000000);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "73.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "73.0.1");
user_pref("extensions.lastPlatformVersion", "73.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"8e138b32-364b-4486-9d88-b45f0a8de1ae\",\"formautofill@mozilla.org\":\"bce141c1-d54f-4546-9e90-05aeec7e2e2b\",\"webcompat@mozilla.org\":\"331c8a61-ddff-453a-96cc-47a80da5fbf8\",\"doh-rollout@mozilla.org\":\"524702cd-a4a8-4eb2-9a54-df8afa4ee2ad\",\"webcompat-reporter@mozilla.org\":\"c0322293-fd17-4c51-b0a1-d360bd52bc8e\",\"default-theme@mozilla.org\":\"fd76c449-b20b-4c30-907b-92ddd8b11ea9\",\"google@search.mozilla.org\":\"b115222a-f901-4cc3-aba5-e63597773607\",\"amazondotcom@search.mozilla.org\":\"8a965051-9079-4692-8db6-b88014a0a56d\",\"bing@search.mozilla.org\":\"c0f4c910-df95-4beb-9094-bfec9ce42fdf\",\"ddg@search.mozilla.org\":\"03d3db02-f7e9-48b6-8870-a4e6f76f28c3\",\"ebay@search.mozilla.org\":\"c35da25d-30af-489d-bcdd-d97296cb4abe\",\"twitter@search.mozilla.org\":\"723e02a3-d456-45e0-8233-662a6c95a74c\",\"wikipedia@search.mozilla.org\":\"3c9e3fd5-7651-4c90-9c23-cfb62cb4d78f\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("gfx.blacklist.layers.opengl", 4);
user_pref("gfx.blacklist.layers.opengl.failureid", "FEATURE_FAILURE_SOFTWARE_GL");
user_pref("media.gmp-manager.buildID", "20180406121424");
user_pref("media.gmp-manager.lastCheck", 1576928372);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "62158460-d0b2-4113-a2ec-485f2061ef40");
user_pref("security.sandbox.plugin.tempDirSuffix", "36947005-0624-4275-b1fd-da146914d902");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1597990390);
user_pref("toolkit.telemetry.cachedClientID", "b048fd15-cc73-4ff1-9176-796c24b3d5fe");
user_pref("toolkit.telemetry.previousBuildID", "20200217142647");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
